version: '3.9'

services:
  # Django Web Application
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings  # Define Django settings module
      - DEBUG=True  # Set to False in production
      - DATABASE_URL=postgres://postgres@db:5432/mydatabase  # Example DB connection

  # PostgreSQL Database
  db:
    image: postgres:17-alpine
    restart: always
    container_name: mydatabase
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]

volumes:
  postgres_data:
